version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: system_oceniania_gier
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./certs:/etc/mysql/certs
    command: >
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    ports:
      - "8811:3306"
